### ISSUE TITLE
Running Task List

### ISSUE THREAD

**Issue by Xypter** [Xypter/sgxp#1]
# 1. Initial Setup

## Convert all usable CSS to Astro
- [x] Update custom css icon for sprite section
- [x] Fix theme dropdown menu
- [ ] Add Sticky nav on scroll with logo movement
- [ ] Add Soda-kan slogan
- [ ] Simplify CSS to flex from desktop to mobile devices

## Convert old pages to new code
- [x] Convert PHP snippets into repeatable astro components
- [x] Apply all old pages to render correctly in nav

## Create CMS
- [x] Setup back end in Digital Ocean
- [x] Create working webhook with github
- [ ] Tie Netlify deploy with API and have live data be served
- [ ] Create new entries in sprite section
- [ ] Replicate and create old legacy news to fit current format

## Bonus
- [ ] Restore old forum in Digital Ocean for easy access

# 2. Building the Tool Kit
## General Functionality
- [ ] All user accounts assignable to specific permissions (posting to the news feed, posting a comic, posting to the sprite section)
- [ ] Administrator should be able to manually assign sprite sheet/comic to user linking back to their profile.

### Login Landing Page
- [ ] Email
- [ ] Password
- [ ] Log in using Discord
- [ ] Not a member? Register
### Authentication
- [ ] Create system that stores user information on the back end
- [ ] Create system that grabs and stores user information from the Discord API

### User Information
- [ ] Date Joined
- [ ] Last Visited
- [ ] Total Sheets
- [ ] Reputation/Status (Sprite Shogun, Sprite God, etc...) 
### User Management
- [ ] List of all users, with the option to filter and sort by join date, alphabetical order, or specific search.
- [ ] Option to edit user info such as email/username/password
- [ ] Option to take action on user (ban, promote to mod, etc...)
### Sprite Sheet Approval System
- [ ] Drop Down list of upload requests, with a filter to organize by awaiting/rejected/approved/posted
- [ ] Option to take action on individual upload
- [ ] Option to take action on multiple selected 'awaiting' sheets
- [ ] Option to edit upload information
- [ ] Option to assign sheet that was manually uploaded
### Theme Builder
- [ ] Drop down list of each theme css stored in the system
- [ ] Option to add new css via text box
- [ ] Option to preview theme before launch

### Sprites Page
- [ ] Outline the system hierarchy for how icons are initially organized
- [ ] Outline how sheets will be uploaded and stored by the server
- [ ] Create filter dropdown allowing users to organize sheets by user/tag/character/etc...
- [ ] Create a sheet upload button the appears when a user is logged in
### Comics Page
- [ ] Outline general layout of buttons and elements
